services:


  web:
    build: .

    command: gunicorn --config gunicorn_config.py resumes.wsgi:application 
    volumes:
      - .:/app

    expose:
      - 8000

    env_file:
      - .env

  
  nginx:
    image: nginx:latest
    ports:
      - 8000:80

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/static
      - ./media:/app/media

    depends_on:
      - web