# Generated by Django 5.0.6 on 2024-06-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.ManyToManyField(to='resumes_api.experience'),
        ),
    ]
