# Generated by Django 5.0.6 on 2024-06-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_api', '0004_generalinfo_image_remove_resume_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.ManyToManyField(to='resumes_api.experience'),
        ),
    ]
