# Generated by Django 5.0.6 on 2024-06-26 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_api', '0005_remove_resume_experience_resume_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resumes_api.experience'),
            preserve_default=False,
        ),
    ]
