# Generated by Django 5.0.6 on 2024-06-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_api', '0006_remove_resume_experience_resume_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
