# Generated by Django 5.0.6 on 2024-06-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_api', '0008_remove_resume_experience_resume_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.ManyToManyField(blank=True, to='resumes_api.experience'),
        ),
    ]
