# Generated by Django 5.0.6 on 2024-06-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_api', '0009_alter_resume_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
    ]
