# Generated by Django 5.0.6 on 2024-06-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_api', '0010_remove_resume_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.ManyToManyField(blank=True, to='resumes_api.experience'),
        ),
    ]
