name: resume_api-CI/CD


on:
   
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]

  
  env:
    DB_URL: ${{ secrets.DB_URL }}
    SECRET_KEY: ${{ secrets.SECRET_KEY }}


jobs:
  build:
    runs_on: ubuntu_latest

    steps:
      - uses: actions/checkout@v4

      - name: install python 3.12.4
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.4

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: run migrations
        run: |
          python manage.py migrate
      
      - name: run tests
        run: python manage.py test
